import 'fake-indexeddb/auto'
import { beforeEach,describe,expect,it } from 'vitest'
import { fromBase64Url } from '../security/crypto/bytes'
import { __localDatabaseTesting,getAllRecords,getRecord,getRecordConflict,LOCAL_STORES,mergeRecord,putRecord,UnresolvedRecordConflictError } from '../data/localDatabase'

const pain=(id:string,note:string)=>({id,startedAt:'2026-09-16T10:00:00.000Z',endedAt:'',locations:[],intensity:4,qualities:[],cause:'',occursWhen:'',note,createdAt:'2026-09-16T10:00:00.000Z',updatedAt:'2026-09-16T10:00:00.000Z'})
function byteSort(ids:string[]):string[]{return [...ids].sort((left,right)=>{const a=fromBase64Url(left),b=fromBase64Url(right);for(let i=0;i<Math.min(a.length,b.length);i++){if(a[i]!==b[i])return a[i]!-b[i]!}return a.length-b.length})}
async function reset(){await __localDatabaseTesting.resetForTesting();await new Promise<void>((resolve,reject)=>{const request=indexedDB.deleteDatabase('eds-diary');request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error);request.onblocked=()=>reject(new Error('blocked'))})}

describe('explicit record conflict merge',()=>{beforeEach(reset)
it('preserves sibling heads, blocks implicit reads/writes, and resolves only through an all-head merge',async()=>{await putRecord(LOCAL_STORES.painEntries,pain('local-seed','R5'));const initial=(await getAllRecords<ReturnType<typeof pain>>(LOCAL_STORES.painEntries))[0]!,recordId=initial.id;let revisions=(await __localDatabaseTesting.revisions()).filter(revision=>revision.record_id===recordId),base=revisions[0]!;await putRecord(LOCAL_STORES.painEntries,{...initial,note:'R6A',updatedAt:'2026-09-16T11:00:00.000Z'});revisions=(await __localDatabaseTesting.revisions()).filter(revision=>revision.record_id===recordId);const headA=revisions.find(revision=>revision.parent_revision_ids.includes(base.revision_id))!;await __localDatabaseTesting.appendTestBranch(LOCAL_STORES.painEntries,{...initial,note:'R6B',updatedAt:'2026-09-16T12:00:00.000Z'},base.revision_id);const conflict=await getRecordConflict<Record<string,unknown>>(LOCAL_STORES.painEntries,recordId);expect(conflict?.heads).toHaveLength(2);expect(new Set(conflict?.heads.map(head=>(head.data as {note?:string}|null)?.note))).toEqual(new Set(['R6A','R6B']));await expect(getRecord(LOCAL_STORES.painEntries,recordId)).rejects.toBeInstanceOf(UnresolvedRecordConflictError);await expect(getAllRecords(LOCAL_STORES.painEntries)).rejects.toBeInstanceOf(UnresolvedRecordConflictError);await expect(putRecord(LOCAL_STORES.painEntries,{...initial,note:'implicit winner',updatedAt:'2026-09-16T13:00:00.000Z'})).rejects.toBeInstanceOf(UnresolvedRecordConflictError);const headIds=conflict!.heads.map(head=>head.revisionId);await mergeRecord(LOCAL_STORES.painEntries,{...initial,note:'R7 merged',updatedAt:'2026-09-16T14:00:00.000Z'});revisions=(await __localDatabaseTesting.revisions()).filter(revision=>revision.record_id===recordId);const merged=revisions.at(-1)!;expect(merged.parent_revision_ids).toEqual(byteSort(headIds));expect(revisions.map(revision=>revision.revision_id)).toEqual(expect.arrayContaining([base.revision_id,headA.revision_id,...headIds,merged.revision_id]));expect(await getRecord<{id:string;note:string}>(LOCAL_STORES.painEntries,recordId)).toMatchObject({id:recordId,note:'R7 merged'});expect(await getRecordConflict(LOCAL_STORES.painEntries,recordId)).toBeNull()})})
