import { describe,expect,it } from 'vitest'
import { createOrReconcile, reconcileCreation, runCreationStateMachine, type CreationState } from '../sync/core/creation'
import { InMemoryTransport } from '../sync/testing/InMemoryTransport'
import { GoogleSheetsSingleWriterProfileCodec } from '../sync/google/GoogleSheetsSingleWriterProfileCodec'
import { createBackup,testRestoreBackup } from '../security/backup'
import { deriveEpochSalt, randomBytes } from '../security/crypto/core'
import { base64Url } from '../security/crypto/bytes'
import { TestRemoteVerifier } from '../sync/testing/TestRemoteVerifier'
import type { FullRemoteVerifier } from '../sync/core/remoteVerifier'
describe('create reconciliation',()=>{it('binds only one authenticated candidate and stops ambiguity',async()=>{const t=new InMemoryTransport(),c=new GoogleSheetsSingleWriterProfileCodec(new TestRemoteVerifier()),manifest=['sync-v5','5','AAAAAAAAAAAAAAAA','AAAAAAAAAAAAAAAAAAAAAA'];t.remotes.set('loc',{manifest,rows:[]});const fingerprint=(await c.verifyRemote({manifest,rows:[]})).manifestFingerprint;const base={locator:'loc',manifestFingerprint:fingerprint,status:'creation_pending' as const,remoteId:null};expect((await createOrReconcile(base,manifest,t,c)).status).toBe('bound');t.remotes.set('loc-copy',{manifest,rows:[]});expect((await reconcileCreation(base,t,c)).status).toBe('ambiguous')})})
describe('create crash reconciliation',()=>{it('discovers an already-created candidate before retrying create',async()=>{class CountingTransport extends InMemoryTransport{creates=0;override async create(locator:string,cells:readonly string[]){this.creates++;return super.create(locator,cells)}}const transport=new CountingTransport(),codec=new GoogleSheetsSingleWriterProfileCodec(new TestRemoteVerifier()),manifest=['sync-v5','5','AAAAAAAAAAAAAAAA','AAAAAAAAAAAAAAAAAAAAAA'];transport.remotes.set('loc-existing',{manifest:[],rows:[]});let saved:CreationState|null={locator:'loc',manifestFingerprint:(await codec.verifyRemote({manifest,rows:[]})).manifestFingerprint,status:'create_pending',remoteId:null,manifest,manifestBytes:JSON.stringify(manifest),candidateIds:[]};const persistence={read:async()=>saved,write:async(value:CreationState)=>{saved=structuredClone(value)}};const result=await runCreationStateMachine(saved,manifest,transport,codec,persistence);expect(transport.creates).toBe(0);expect(result.status).toBe('bound')})})
describe('bounded encrypted backup',()=>{it('round trips the complete envelope set',async()=>{const rootKey=randomBytes(32),diaryId=base64Url(new Uint8Array(16).fill(1)),epochId=base64Url(new Uint8Array(16).fill(2)),keyId=base64Url(new Uint8Array(16).fill(3)),manifestFingerprint=base64Url(new Uint8Array(32).fill(4)),epochSalt=await deriveEpochSalt(new Uint8Array(16).fill(1),new Uint8Array(16).fill(2)),values=[{envelopeId:base64Url(new Uint8Array(32).fill(5)),iv:base64Url(new Uint8Array(12).fill(6)),ciphertext:base64Url(new Uint8Array(1040).fill(7)),bytesHash:'h'}],context={rootKey,epochSalt,diaryId,epochId,keyId,manifestFingerprint,epochManifestPublic:['sync-v5','5',base64Url(new Uint8Array(12)),base64Url(new Uint8Array(16))]as const,remoteRows:[]as const,localEnvelopes:values,remoteBound:false,createdAt:'2026-09-15T12:00:00.000Z'},backup=await createBackup(context);await expect(testRestoreBackup(context,backup,(()=>undefined) as unknown as FullRemoteVerifier)).rejects.toThrow('production full verifier')})})
