import { describe,expect,it } from 'vitest'
import { createOrReconcile, reconcileCreation, runCreationStateMachine, type CreationState } from '../sync/core/creation'
import { InMemoryTransport } from '../sync/testing/InMemoryTransport'
import { GoogleSheetsSingleWriterProfileCodec } from '../sync/google/GoogleSheetsSingleWriterProfileCodec'
import { createBackup,testRestoreBackup } from '../security/backup'
import { deriveEpochSalt, randomBytes } from '../security/crypto/core'
import { base64Url } from '../security/crypto/bytes'
import { TestRemoteVerifier } from '../sync/testing/TestRemoteVerifier'
import type { FullRemoteVerifier } from '../sync/core/remoteVerifier'
describe('create reconciliation',()=>{it('binds only one authenticated candidate and stops ambiguity',async()=>{const t=new InMemoryTransport(),c=new GoogleSheetsSingleWriterProfileCodec(new TestRemoteVerifier()),manifest=['sync-v5','5','AAAAAAAAAAAAAAAA','AAAAAAAAAAAAAAAAAAAAAA'];t.remotes.set('loc',{manifest,rows:[]});const fingerprint=(await c.verifyRemote({manifest,rows:[]})).manifestFingerprint;const base={locator:'loc',manifestFingerprint:fingerprint,status:'creation_pending' as const,remoteId:null};expect((await createOrReconcile(base,manifest,t,c)).status).toBe('bound');t.remotes.set('loc-copy',{manifest,rows:[]});expect((await reconcileCreation(base,t,c)).status).toBe('ambiguous')})})
describe('create crash reconciliation',()=>{it('discovers an already-created candidate before retrying create',async()=>{class CountingTransport extends InMemoryTransport{creates=0;override async create(locator:string,cells:readonly string[]){this.creates++;return super.create(locator,cells)}}const transport=new CountingTransport(),codec=new GoogleSheetsSingleWriterProfileCodec(new TestRemoteVerifier()),manifest=['sync-v5','5','AAAAAAAAAAAAAAAA','AAAAAAAAAAAAAAAAAAAAAA'];transport.remotes.set('loc-existing',{manifest:[],rows:[]});let saved:CreationState|null={locator:'loc',manifestFingerprint:(await codec.verifyRemote({manifest,rows:[]})).manifestFingerprint,status:'create_pending',remoteId:null,manifest,manifestBytes:JSON.stringify(manifest),candidateIds:[]};const persistence={read:async()=>saved,write:async(value:CreationState)=>{saved=structuredClone(value)}};const result=await runCreationStateMachine(saved,manifest,transport,codec,persistence);expect(transport.creates).toBe(0);expect(result.status).toBe('bound')})})
describe('creation persistent fault matrix',()=>{it('resumes every durable intent/readback phase without issuing a second create',async()=>{
  const phases=['planned','discovery_verified','create_pending','candidate_known','manifest_pending','manifest_verified','properties_pending','properties_verified','final_reconcile','bound'] as const
  for(const crashPhase of phases){
    class CountingTransport extends InMemoryTransport{creates=0;override async create(locator:string,cells:readonly string[]){this.creates++;await super.create(locator,cells);if(this.creates===1)throw new Error('lost create response')}}
    const transport=new CountingTransport(),codec=new GoogleSheetsSingleWriterProfileCodec(new TestRemoteVerifier()),manifest=['sync-v5','5','AAAAAAAAAAAAAAAA','AAAAAAAAAAAAAAAAAAAAAA'],fingerprint=(await codec.verifyRemote({manifest,rows:[]})).manifestFingerprint,initial:CreationState={locator:`matrix-${crashPhase}`,manifestFingerprint:fingerprint,status:'planned',remoteId:null,expectedProperties:{app_format:'sync-v5',epoch_locator:`matrix-${crashPhase}`}};let saved:CreationState|null=null,crashed=false
    const persistence={read:async()=>saved,write:async(value:CreationState)=>{saved=structuredClone(value);if(value.status===crashPhase&&!crashed){crashed=true;throw new Error('injected crash')}}}
    let result:CreationState|undefined;for(let attempt=0;attempt<3&&!result;attempt++){try{result=await runCreationStateMachine(initial,manifest,transport,codec,persistence)}catch(error){expect(error).toHaveProperty('message','injected crash')}}
    expect(result?.status,crashPhase).toBe('bound');expect(transport.creates,crashPhase).toBeLessThanOrEqual(1)
  }
})
it('reconciles duplicate verified candidates from a persisted ambiguous state',async()=>{const transport=new InMemoryTransport(),codec=new GoogleSheetsSingleWriterProfileCodec(new TestRemoteVerifier()),manifest=['sync-v5','5','AAAAAAAAAAAAAAAA','AAAAAAAAAAAAAAAAAAAAAA'],fingerprint=(await codec.verifyRemote({manifest,rows:[]})).manifestFingerprint,initial:CreationState={locator:'ambiguous',manifestFingerprint:fingerprint,status:'ambiguous',remoteId:null,manifest,manifestBytes:JSON.stringify(manifest),expectedProperties:{app_format:'sync-v5',epoch_locator:'ambiguous'},candidateIds:['ambiguous-a','ambiguous-b']};transport.remotes.set('ambiguous-a',{manifest,rows:[]});transport.remotes.set('ambiguous-b',{manifest,rows:[]});transport.properties.set('ambiguous-a',initial.expectedProperties!);transport.properties.set('ambiguous-b',initial.expectedProperties!);let saved:CreationState|null=structuredClone(initial);const persistence={read:async()=>saved,write:async(value:CreationState)=>{saved=structuredClone(value)}};const result=await runCreationStateMachine(initial,manifest,transport,codec,persistence);expect(result.status).toBe('bound');expect(transport.remotes.size).toBe(1);expect(result.remoteId).toBe([...transport.remotes.keys()][0])})
it('stays fail-closed when a discovered candidate conflicts',async()=>{const transport=new InMemoryTransport(),codec=new GoogleSheetsSingleWriterProfileCodec(new TestRemoteVerifier()),manifest=['sync-v5','5','AAAAAAAAAAAAAAAA','AAAAAAAAAAAAAAAAAAAAAA'],fingerprint=(await codec.verifyRemote({manifest,rows:[]})).manifestFingerprint,initial:CreationState={locator:'conflict',manifestFingerprint:fingerprint,status:'planned',remoteId:null,expectedProperties:{app_format:'sync-v5',epoch_locator:'conflict'}};transport.remotes.set('conflict-good',{manifest,rows:[]});transport.properties.set('conflict-good',initial.expectedProperties!);transport.remotes.set('conflict-bad',{manifest,rows:[['unexpected','row','data']]});let saved:CreationState|null=null;const persistence={read:async()=>saved,write:async(value:CreationState)=>{saved=structuredClone(value)}};const result=await runCreationStateMachine(initial,manifest,transport,codec,persistence);expect(result.status).toBe('ambiguous');expect(transport.remotes.size).toBe(2)})})
describe('bounded encrypted backup',()=>{it('round trips the complete envelope set',async()=>{const rootKey=randomBytes(32),diaryId=base64Url(new Uint8Array(16).fill(1)),epochId=base64Url(new Uint8Array(16).fill(2)),keyId=base64Url(new Uint8Array(16).fill(3)),manifestFingerprint=base64Url(new Uint8Array(32).fill(4)),epochSalt=await deriveEpochSalt(new Uint8Array(16).fill(1),new Uint8Array(16).fill(2)),values=[{envelopeId:base64Url(new Uint8Array(32).fill(5)),iv:base64Url(new Uint8Array(12).fill(6)),ciphertext:base64Url(new Uint8Array(1040).fill(7)),bytesHash:'h'}],context={rootKey,epochSalt,diaryId,epochId,keyId,manifestFingerprint,epochManifestPublic:['sync-v5','5',base64Url(new Uint8Array(12)),base64Url(new Uint8Array(16))]as const,remoteRows:[]as const,localEnvelopes:values,remoteBound:false,createdAt:'2026-09-15T12:00:00.000Z'},backup=await createBackup(context);await expect(testRestoreBackup(context,backup,(()=>undefined) as unknown as FullRemoteVerifier)).rejects.toThrow('production full verifier')})})
