import 'fake-indexeddb/auto'
import { beforeEach, describe, expect, it, vi } from 'vitest'

async function removeDatabase():Promise<void>{await new Promise<void>((resolve,reject)=>{const request=indexedDB.deleteDatabase('eds-diary');request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error);request.onblocked=()=>reject(new Error('delete blocked'))})}
async function transactionDone(tx:IDBTransaction):Promise<void>{await new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
async function clearLegacyMappings(raw:IDBDatabase,storeName:string):Promise<void>{const tx=raw.transaction(storeName,'readwrite'),store=tx.objectStore(storeName),request=store.openCursor();await new Promise<void>((resolve,reject)=>{request.onsuccess=()=>{const cursor=request.result;if(!cursor){resolve();return}if(typeof cursor.key==='string'&&cursor.key.startsWith('map:'))cursor.delete();cursor.continue()};request.onerror=()=>reject(request.error)});await transactionDone(tx)}
const activity=(id:string,note='device A')=>({id,date:'2026-09-16',startTime:'10:00',endTime:'11:00',isOngoing:false,activityName:'Spaziergang',color:'#cbe7ca',note,createdAt:'2026-09-16T08:00:00.000Z',updatedAt:'2026-09-16T08:00:00.000Z'})

describe('multi-device logical identities',()=>{beforeEach(async()=>{vi.resetModules();await removeDatabase()})
it('uses the encrypted canonical record id without a device-local mapping',async()=>{const db=await import('../data/localDatabase');await db.putRecord(db.LOCAL_STORES.activityEntries,activity('activity-local-a'));const first=await db.getAllRecords<ReturnType<typeof activity>>(db.LOCAL_STORES.activityEntries);expect(first).toHaveLength(1);const canonicalId=first[0]!.id;expect(canonicalId).toMatch(/^[A-Za-z0-9_-]{22}$/);expect(canonicalId).not.toBe('activity-local-a');const raw=await db.__localDatabaseTesting.openDatabase();await clearLegacyMappings(raw,db.__localDatabaseTesting.STORES.migration);expect(await db.getRecord<ReturnType<typeof activity>>(db.LOCAL_STORES.activityEntries,canonicalId)).toMatchObject({id:canonicalId,note:'device A'});await db.putRecord(db.LOCAL_STORES.activityEntries,{...first[0]!,note:'device B edit',updatedAt:'2026-09-16T09:00:00.000Z'});const after=await db.getAllRecords<ReturnType<typeof activity>>(db.LOCAL_STORES.activityEntries);expect(after).toHaveLength(1);expect(after[0]).toMatchObject({id:canonicalId,note:'device B edit'})})
it('reconstructs both settings singleton ids without the local migration map',async()=>{const db=await import('../data/localDatabase');await db.putRecord(db.LOCAL_STORES.settings,{id:'activity-types',values:[{name:'Spaziergang',color:'#cbe7ca'}]});await db.putRecord(db.LOCAL_STORES.settings,{id:'pain-types',values:['Stechend']});const raw=await db.__localDatabaseTesting.openDatabase();await clearLegacyMappings(raw,db.__localDatabaseTesting.STORES.migration);expect(await db.getRecord<{id:string;values:unknown[]}>(db.LOCAL_STORES.settings,'activity-types')).toMatchObject({id:'activity-types'});expect(await db.getRecord<{id:string;values:unknown[]}>(db.LOCAL_STORES.settings,'pain-types')).toMatchObject({id:'pain-types'})})
})
