import { useEffect, useState } from 'react'
import { listRecordConflicts, mergeRecord, type StoreRecordConflict } from '../../data/localDatabase'
import './ConflictResolutionSettings.css'

export function ConflictResolutionSettings() {
  const [conflicts,setConflicts]=useState<StoreRecordConflict[]>([]),[drafts,setDrafts]=useState<Record<string,string>>({}),[status,setStatus]=useState('')
  const refresh=()=>void listRecordConflicts().then(setConflicts).catch(cause=>setStatus(cause instanceof Error?cause.message:'Konflikte konnten nicht geprüft werden.'))
  useEffect(refresh,[])
  function choose(conflict:StoreRecordConflict,index:number):void{const data=conflict.heads[index]?.data;setDrafts(current=>({...current,[conflict.recordId]:JSON.stringify({id:conflict.id,...(data&&typeof data==='object'?data as Record<string,unknown>:{})},null,2)}))}
  async function resolve(conflict:StoreRecordConflict):Promise<void>{try{const parsed=JSON.parse(drafts[conflict.recordId]??'') as unknown;if(!parsed||typeof parsed!=='object'||Array.isArray(parsed)||(parsed as {id?:unknown}).id!==conflict.id)throw new Error('Das Ergebnis muss ein Objekt mit unveränderter fachlicher ID sein.');await mergeRecord(conflict.store,parsed as {id:string});setStatus('Konflikt durch eine neue Merge-Revision aufgelöst.');refresh()}catch(cause){setStatus(cause instanceof Error?cause.message:'Konfliktauflösung fehlgeschlagen.')}}
  return <details className="conflict-settings" onToggle={event=>{if(event.currentTarget.open)refresh()}}><summary>Fachliche Konflikte <span>{conflicts.length?`${conflicts.length} offen`:'keine erkannt'}</span></summary><p>Es wird niemals automatisch eine Variante gewählt. Vergleiche alle Heads – einschließlich gelöschter Varianten – und lege den endgültigen Zustand ausdrücklich fest.</p>{conflicts.map(conflict=><section key={conflict.recordId} className="conflict-settings__case"><h3>{conflict.store} · {conflict.id}</h3><div className="conflict-settings__heads">{conflict.heads.map((head,index)=><article key={head.revisionId}><h4>Variante {index+1}: {head.status==='deleted'?'Gelöscht':'Aktiv'}</h4><pre>{JSON.stringify(head.data,null,2)??'null'}</pre><button type="button" onClick={()=>choose(conflict,index)}>Als Ausgangspunkt wählen</button></article>)}</div><label>Endgültiger fachlicher Zustand (JSON)<textarea rows={12} value={drafts[conflict.recordId]??''} onChange={event=>setDrafts(current=>({...current,[conflict.recordId]:event.target.value}))}/></label><button type="button" disabled={!drafts[conflict.recordId]} onClick={()=>void resolve(conflict)}>Alle Heads sicher zusammenführen</button></section>)}<p role="status" aria-live="polite">{status}</p></details>
}
