import fs from 'node:fs'

function read(path){return fs.readFileSync(path,'utf8')}
function write(path,value){fs.writeFileSync(path,value)}
function replaceOnce(source,before,after,label){
  if(!source.includes(before)) throw new Error(`Missing patch target: ${label}`)
  return source.replace(before,after)
}

{
  const path='src/sync/core/coordinator.ts'
  let s=read(path)
  s=replaceOnce(s,
`  commitDurable(envelopeId: string, anchor: RemoteAnchor, expectedGeneration: number): Promise<void>\n`,
`  commitVerifiedPull?(rows: ReadonlyArray<readonly string[]>, anchor: RemoteAnchor, expectedGeneration: number): Promise<number>\n  commitDurable(envelopeId: string, anchor: RemoteAnchor, expectedGeneration: number): Promise<void>\n`,
'coordinator store verified pull')
  s=replaceOnce(s,
`      await assertExtendsAnchor(await this.store.readAnchor(), this.diaryId, this.epochId, snapshot.rows)\n      this.verifiedGeneration = await this.store.generation()\n      this.verifiedRows = snapshot.rows\n`,
`      await assertExtendsAnchor(await this.store.readAnchor(), this.diaryId, this.epochId, snapshot.rows)\n      const generation = await this.store.generation()\n      const anchor = await createAnchor(this.diaryId, this.epochId, snapshot.rows)\n      this.verifiedGeneration = this.store.commitVerifiedPull\n        ? await this.store.commitVerifiedPull(snapshot.rows, anchor, generation)\n        : generation\n      this.verifiedRows = snapshot.rows\n`,
'pull persists verified snapshot')
  write(path,s)
}

{
  const path='src/data/localDatabase.ts'
  let s=read(path)
  s=replaceOnce(s,`const DATABASE_VERSION = 7`,`const DATABASE_VERSION = 8`,'db version')
  s=replaceOnce(s,
`  envelopes: 'envelopes', revisions: 'revisions', outbox: 'outbox', state: 'epochSecurityState',\n`,
`  envelopes: 'envelopes', outbox: 'outbox', state: 'epochSecurityState',\n`,
'remove revisions store constant')
  s=replaceOnce(s,`interface StoredRevision { id:string; epochId:string; sequence:number; revision:Revision }\n`,``,'remove stored revision type')
  s=replaceOnce(s,
`    for(const name of LEGACY_STORES)if(!db.objectStoreNames.contains(name))db.createObjectStore(name,{keyPath:'id'})\n    for(const name of Object.values(STORES))if(!db.objectStoreNames.contains(name)){const store=db.createObjectStore(name,{keyPath:'id'});if(name===STORES.envelopes||name===STORES.revisions||name===STORES.outbox)store.createIndex('byEpoch','epochId')}\n`,
`    for(const name of LEGACY_STORES)if(!db.objectStoreNames.contains(name))db.createObjectStore(name,{keyPath:'id'})\n    if(db.objectStoreNames.contains('revisions'))db.deleteObjectStore('revisions')\n    for(const name of Object.values(STORES))if(!db.objectStoreNames.contains(name)){const store=db.createObjectStore(name,{keyPath:'id'});if(name===STORES.envelopes||name===STORES.outbox)store.createIndex('byEpoch','epochId')}\n    if(request.transaction&&db.objectStoreNames.contains(STORES.operations)){const operations=request.transaction.objectStore(STORES.operations),cursor=operations.openCursor();cursor.addEventListener('success',()=>{const current=cursor.result;if(!current)return;if(typeof current.key==='string'&&current.key.startsWith('rotation-artifact:revision:'))current.delete();current.continue()})}\n`,
'upgrade removes plaintext caches')
  s=replaceOnce(s,
`  const id=String(value.id??'');if(!id)throw new Error('Record id is required.');const recordId=await recordIdentity(loaded.context,store,id),revisions=await verifiedEnvelopeRevisions(db)\n  const graph=validateRevisionGraph(revisions),heads=[...(graph.headsByRecord.get(recordId)??[])],profile=profileFor(store,id),revisionId=fixedRevisionId??base64Url(randomBytes(32))\n`,
`  const id=String(value.id??'');if(!id)throw new Error('Record id is required.');const revisions=await verifiedEnvelopeRevisions(db),profile=profileFor(store,id),recordId=revisions.some(revision=>revision.record_id===id&&revision.record_type===profile.recordType&&revision.record_schema===profile.recordSchema)?id:await recordIdentity(loaded.context,store,id);await rememberMapping(db,store,recordId,id)\n  const graph=validateRevisionGraph(revisions),heads=[...(graph.headsByRecord.get(recordId)??[])],revisionId=fixedRevisionId??base64Url(randomBytes(32));if(heads.length>1)throw new Error('Unresolved record conflict; explicit merge is required.')\n`,
'conflict-safe record identity')
  s=replaceOnce(s,
`      const tag=await stateTag(loaded.rootKey,loaded.epochSalt,nextState),tx=db.transaction([STORES.envelopes,STORES.revisions,STORES.outbox,STORES.reservations,STORES.state],'readwrite');tx.objectStore(STORES.envelopes).add({...envelope,id:envelope.envelopeId,epochId:loaded.context.epochId,localSeq:sequence,rowBytes} satisfies StoredEnvelope);tx.objectStore(STORES.revisions).add({id:revisionId,epochId:loaded.context.epochId,sequence,revision} satisfies StoredRevision);tx.objectStore(STORES.outbox).add({id:envelope.envelopeId,epochId:loaded.context.epochId,envelopeId:envelope.envelopeId,rowBytes,status:'prepared'} satisfies StoredOutbox);tx.objectStore(STORES.reservations).put({id:envelope.envelopeId,epochId:loaded.context.epochId,status:'consumed'});tx.objectStore(STORES.state).put({id:loaded.context.epochId,state:nextState,tag} satisfies StoredState);await complete(tx)\n`,
`      const tag=await stateTag(loaded.rootKey,loaded.epochSalt,nextState),tx=db.transaction([STORES.envelopes,STORES.outbox,STORES.reservations,STORES.state],'readwrite');tx.objectStore(STORES.envelopes).add({...envelope,id:envelope.envelopeId,epochId:loaded.context.epochId,localSeq:sequence,rowBytes} satisfies StoredEnvelope);tx.objectStore(STORES.outbox).add({id:envelope.envelopeId,epochId:loaded.context.epochId,envelopeId:envelope.envelopeId,rowBytes,status:'prepared'} satisfies StoredOutbox);tx.objectStore(STORES.reservations).put({id:envelope.envelopeId,epochId:loaded.context.epochId,status:'consumed'});tx.objectStore(STORES.state).put({id:loaded.context.epochId,state:nextState,tag} satisfies StoredState);await complete(tx)\n`,
'normal write removes plaintext revision')
  s=replaceOnce(s,
`export async function putRecords<T extends{id:string}>(storeName:LocalStoreName,values:readonly T[]):Promise<void>{if(!values.length)return;await ready();const db=await openDatabase(),loaded=await loadEpoch(db);await withDiaryLock(loaded.context.diaryId,async()=>{for(const value of values){const recordId=await recordIdentity(loaded.context,storeName,value.id);await rememberMapping(db,storeName,recordId,value.id);await persistRevision(db,storeName,value as unknown as Record<string,unknown>)}})}\n`,
`export async function putRecords<T extends{id:string}>(storeName:LocalStoreName,values:readonly T[]):Promise<void>{if(!values.length)return;await ready();const db=await openDatabase(),loaded=await loadEpoch(db);await withDiaryLock(loaded.context.diaryId,async()=>{for(const value of values)await persistRevision(db,storeName,value as unknown as Record<string,unknown>)})}\n`,
'putRecords mapping moves into persist')

  const insertion=`\nexport async function commitVerifiedPull(epochId:string,remoteRows:ReadonlyArray<readonly string[]>,anchor:RemoteAnchor,expectedGeneration:number,wrapId?:string):Promise<number>{const db=await openDatabase(),loaded=await loadEpochFor(db,epochId,wrapId);return withDiaryLock(loaded.context.diaryId,async()=>{const current=await loadEpochFor(db,epochId,wrapId);if(current.state.operation_generation!==expectedGeneration)throw new Error('Stale verified pull generation.');if(anchor.covered_row_count!==remoteRows.length)throw new Error('Verified pull anchor does not cover the supplied snapshot.');const read=db.transaction(STORES.envelopes,'readonly'),stored=await result<StoredEnvelope[]>(read.objectStore(STORES.envelopes).index('byEpoch').getAll(epochId));await complete(read);const localById=new Map(stored.map(item=>[item.envelopeId,item] as const)),remoteById=new Map<string,string>(),additions:StoredEnvelope[]=[];let sequence=current.state.local_journal_count,hash=current.state.local_journal_hash;for(const row of remoteRows){if(row.length!==3)throw new Error('Invalid verified remote row.');const [envelopeId,iv,ciphertext]=row,rowBytes=decodeUtf8(canonicalBytes([...row])),priorRemote=remoteById.get(envelopeId);if(priorRemote!==undefined){if(priorRemote!==rowBytes)throw new Error('Envelope ID exists with different bytes.');continue}remoteById.set(envelopeId,rowBytes);const prior=localById.get(envelopeId);if(prior){if(prior.rowBytes!==rowBytes)throw new Error('Envelope ID exists with different bytes.');continue}const envelope:PreparedEnvelope={envelopeId,iv,ciphertext,bytesHash:base64Url(await sha256(canonicalBytes([envelopeId,iv,ciphertext])))},revision=await openEnvelope(current.rootKey,current.epochSalt,{diaryId:current.context.diaryId,epochId:current.context.epochId},envelope);if(revision.record_status!=='deleted')validateDomainData(DOMAIN_SCHEMAS[revision.record_schema],revision.record_data);sequence++;hash=await journalNext(hash,sequence,envelope);additions.push({...envelope,id:envelopeId,epochId,localSeq:sequence,rowBytes})}const state={...current.state,remote_anchor:anchor,local_journal_count:sequence,local_journal_hash:hash,operation_generation:current.state.operation_generation+1},tag=await stateTag(current.rootKey,current.epochSalt,state),tx=db.transaction([STORES.envelopes,STORES.state],'readwrite');for(const item of additions)tx.objectStore(STORES.envelopes).add(item);tx.objectStore(STORES.state).put({id:epochId,state,tag} satisfies StoredState);await complete(tx);return state.operation_generation})}\n`
  s=replaceOnce(s,
`export async function commitDurableAck(epochId:string,envelopeId:string,expectedGeneration:number,anchor:EpochLocalSecurityState['remote_anchor'],wrapId?:string):Promise<void>{`,
`${insertion}\nexport async function commitDurableAck(epochId:string,envelopeId:string,expectedGeneration:number,anchor:EpochLocalSecurityState['remote_anchor'],wrapId?:string):Promise<void>{`,
'insert verified pull persistence')
  s=replaceOnce(s,
`  async generation():Promise<number>{return(await loadEpochFor(await openDatabase(),this.epochId,this.wrapId)).state.operation_generation}\n`,
`  async generation():Promise<number>{return(await loadEpochFor(await openDatabase(),this.epochId,this.wrapId)).state.operation_generation}\n  commitVerifiedPull(rows:ReadonlyArray<readonly string[]>,anchor:RemoteAnchor,expectedGeneration:number):Promise<number>{return commitVerifiedPull(this.epochId,rows,anchor,expectedGeneration,this.wrapId)}\n`,
'coordinator store verified pull implementation')
  s=replaceOnce(s,
`  async rotationRevision(id:string,create:()=>Revision):Promise<Revision>{const existing=await this.artifact<Revision>(\`revision:\${id}\`);if(existing)return existing;const revision=create();validateRevision(revision);await this.putArtifact(\`revision:\${id}\`,revision);return(await this.artifact<Revision>(\`revision:\${id}\`))!}\n`,
`  async rotationRevision(_id:string,create:()=>Revision):Promise<Revision>{const revision=create();validateRevision(revision);return revision}\n`,
'rotation revisions no longer persisted plaintext')
  const oldPrepare=`  async prepareRotationEnvelope(_operationId:string,context:EpochContext,revision:Revision):Promise<PreparedEnvelope>{const db=await openDatabase(),existingRevisionTx=db.transaction(STORES.revisions,'readonly'),existingRevision=await result<StoredRevision|undefined>(existingRevisionTx.objectStore(STORES.revisions).get(revision.revision_id));await complete(existingRevisionTx);if(existingRevision){if(decodeUtf8(canonicalBytes(existingRevision.revision as never))!==decodeUtf8(canonicalBytes(revision as never)))throw new Error('Revision ID exists with different bytes.');const all=await this.successorEnvelopes(context.epochId);for(const envelope of all){const opened=await openEnvelope(await this.successorRoot(context.epochId,context.wrapId),await deriveEpochSalt(fromBase64Url(context.diaryId),fromBase64Url(context.epochId)),{diaryId:context.diaryId,epochId:context.epochId},envelope);if(opened.revision_id===revision.revision_id)return envelope}throw new Error('Revision exists without its immutable envelope.')}const rootKey=await this.successorRoot(context.epochId,context.wrapId),salt=await deriveEpochSalt(fromBase64Url(context.diaryId),fromBase64Url(context.epochId));return prepareEnvelope(rootKey,salt,{diaryId:context.diaryId,epochId:context.epochId},revision,{`
  const newPrepare=`  async prepareRotationEnvelope(_operationId:string,context:EpochContext,revision:Revision):Promise<PreparedEnvelope>{const db=await openDatabase(),rootKey=await this.successorRoot(context.epochId,context.wrapId),salt=await deriveEpochSalt(fromBase64Url(context.diaryId),fromBase64Url(context.epochId)),all=await this.successorEnvelopes(context.epochId);for(const envelope of all){const opened=await openEnvelope(rootKey,salt,{diaryId:context.diaryId,epochId:context.epochId},envelope);if(opened.revision_id===revision.revision_id){if(decodeUtf8(canonicalBytes(opened as never))!==decodeUtf8(canonicalBytes(revision as never)))throw new Error('Revision ID exists with different bytes.');return envelope}}return prepareEnvelope(rootKey,salt,{diaryId:context.diaryId,epochId:context.epochId},revision,{`
  s=replaceOnce(s,oldPrepare,newPrepare,'rotation envelope discovers existing revision from ciphertext')
  s=replaceOnce(s,
`const sequence=current.state.local_journal_count+1,next={...current.state,local_journal_count:sequence,local_journal_hash:await journalNext(current.state.local_journal_hash,sequence,envelope),operation_generation:current.state.operation_generation+1},tag=await stateTag(rootKey,salt,next),tx=db.transaction([STORES.envelopes,STORES.revisions,STORES.outbox,STORES.reservations,STORES.state],'readwrite');tx.objectStore(STORES.envelopes).add({...envelope,id:envelope.envelopeId,epochId:context.epochId,localSeq:sequence,rowBytes} satisfies StoredEnvelope);tx.objectStore(STORES.revisions).add({id:revision.revision_id,epochId:context.epochId,sequence,revision} satisfies StoredRevision);tx.objectStore(STORES.outbox).add({id:envelope.envelopeId,epochId:context.epochId,envelopeId:envelope.envelopeId,rowBytes,status:'prepared'} satisfies StoredOutbox);`,
`const sequence=current.state.local_journal_count+1,next={...current.state,local_journal_count:sequence,local_journal_hash:await journalNext(current.state.local_journal_hash,sequence,envelope),operation_generation:current.state.operation_generation+1},tag=await stateTag(rootKey,salt,next),tx=db.transaction([STORES.envelopes,STORES.outbox,STORES.reservations,STORES.state],'readwrite');tx.objectStore(STORES.envelopes).add({...envelope,id:envelope.envelopeId,epochId:context.epochId,localSeq:sequence,rowBytes} satisfies StoredEnvelope);tx.objectStore(STORES.outbox).add({id:envelope.envelopeId,epochId:context.epochId,envelopeId:envelope.envelopeId,rowBytes,status:'prepared'} satisfies StoredOutbox);`,
'rotation envelope removes plaintext revision')
  write(path,s)
}

{
  const path='src/data/productiveRotationService.ts'
  let s=read(path)
  s=replaceOnce(s,
`const digest=async(value:unknown)=>base64Url(await sha256(canonicalBytes(value as never)))\n`,
`const digest=async(value:unknown)=>base64Url(await sha256(canonicalBytes(value as never)))\nconst deterministicId=async(value:unknown,bytes=32)=>base64Url((await sha256(canonicalBytes(value as never))).slice(0,bytes))\n`,
'deterministic rotation ids helper')
  const oldFreeze=`      verifyAndFreezeSource:async()=>{const source=await this.repository.verifiedActiveEpoch();if(source.state.rotation_state_ref?.state!=='source_frozen_verified')throw new Error('Final source snapshot requires a persisted freeze.');const remote=source.state.remote_binding!,material={localEnvelopes:source.envelopes,localHeadRevisionIds:new Set(heads(source.revisions).map(r=>r.revision_id))},verifier=new FullRemoteVerifier({rootKey:source.rootKey,diaryId:source.context.diaryId,epochId:source.context.epochId,expectedManifestFingerprint:source.context.manifestFingerprint,expectedKeyId:source.context.keyId,expectedRecoveryGeneration:source.state.recovery_generation,expectedRecoveryCommitment:source.state.recovery_urs_commitment,expectedGoogleAccountBinding:remote.remote_identity_binding,schemas:DOMAIN_SCHEMA_REGISTRY,oldAnchor:source.state.remote_anchor,...material}),snapshot=await this.transport.read(remote.remote_resource_id);await verifier.verify(snapshot);const hashes=await snapshots(source.revisions);this.source=source;return{anchor:await createAnchor(source.context.diaryId,source.context.epochId,snapshot.rows),semanticSnapshot:hashes.semantic,lineageSnapshot:hashes.lineage}},`
  const newFreeze=`      verifyAndFreezeSource:async()=>{const source=await this.repository.verifiedActiveEpoch();if(source.state.rotation_state_ref?.state!=='source_frozen_verified')throw new Error('Final source snapshot requires a persisted freeze.');const remote=source.state.remote_binding!,material={localEnvelopes:source.envelopes,localHeadRevisionIds:new Set(heads(source.revisions).map(r=>r.revision_id))},verifier=new FullRemoteVerifier({rootKey:source.rootKey,diaryId:source.context.diaryId,epochId:source.context.epochId,expectedManifestFingerprint:source.context.manifestFingerprint,expectedKeyId:source.context.keyId,expectedRecoveryGeneration:source.state.recovery_generation,expectedRecoveryCommitment:source.state.recovery_urs_commitment,expectedGoogleAccountBinding:remote.remote_identity_binding,schemas:DOMAIN_SCHEMA_REGISTRY,oldAnchor:source.state.remote_anchor,...material}),snapshot=await this.transport.read(remote.remote_resource_id);await verifier.verify(snapshot);const anchor=await createAnchor(source.context.diaryId,source.context.epochId,snapshot.rows),store=new IndexedDbCoordinatorStore(source.context.epochId,source.context.wrapId);await store.commitVerifiedPull(snapshot.rows,anchor,await store.generation());const refreshed=await this.repository.verifiedActiveEpoch(),hashes=await snapshots(refreshed.revisions);this.source=refreshed;return{anchor,semanticSnapshot:hashes.semantic,lineageSnapshot:hashes.lineage}},`
  s=replaceOnce(s,oldFreeze,newFreeze,'rotation imports verified remote source')
  const oldCopy=`    for(const head of sourceHashes.heads){if(head.record_status==='deleted')tombstone++;else active++;const revision=await this.repository.rotationRevision(\`${'${state.rotationId}'}:copy:${'${head.revision_id}'}\`,()=>({...head,revision_id:base64Url(randomBytes(32)),parent_revision_ids:[],migration_origin:{sources:[{source_epoch_id:source.context.epochId,source_record_id:head.record_id,source_revision_ids:[head.revision_id]}]},protocol_created_at:state.createdAt}));await this.repository.prepareRotationEnvelope(\`${'${state.rotationId}'}:copy:${'${head.revision_id}'}\`,context,revision);copied++;if(copied===1)await this.hit('after-first-copied-head')}\n    const migrationData=createEpochMigrationData({migration_id:state.rotationId,migration_kind:'normal',source:{source_epoch_id:source.context.epochId,source_manifest_fingerprint:source.context.manifestFingerprint,source_anchor:state.sourceAnchor,source_lineage_snapshot_hash:sourceHashes.lineage,source_semantic_snapshot_hash:sourceHashes.semantic},result_semantic_snapshot_hash:sourceHashes.semantic,active_head_count:active,tombstone_head_count:tombstone}),revision=await this.repository.rotationRevision(\`${'${state.rotationId}'}:migration\`,()=>({record_type:'epoch_migration',record_schema:'epoch-migration-sw-v1',record_id:base64Url(randomBytes(16)),revision_id:base64Url(randomBytes(32)),parent_revision_ids:[],record_status:'control',record_data:migrationData,migration_origin:null,protocol_created_at:state.createdAt}));await this.repository.prepareRotationEnvelope(\`${'${state.rotationId}'}:migration\`,context,revision);await this.hit('after-migration-envelope')\n`
  const newCopy=`    for(const head of sourceHashes.heads){if(head.record_status==='deleted')tombstone++;else active++;const revision:Revision={...head,revision_id:await deterministicId(['rotation-copy-revision-v1',state.rotationId,head.revision_id]),parent_revision_ids:[],migration_origin:{sources:[{source_epoch_id:source.context.epochId,source_record_id:head.record_id,source_revision_ids:[head.revision_id]}]},protocol_created_at:state.createdAt};await this.repository.prepareRotationEnvelope(\`${'${state.rotationId}'}:copy:${'${head.revision_id}'}\`,context,revision);copied++;if(copied===1)await this.hit('after-first-copied-head')}\n    const migrationData=createEpochMigrationData({migration_id:state.rotationId,migration_kind:'normal',source:{source_epoch_id:source.context.epochId,source_manifest_fingerprint:source.context.manifestFingerprint,source_anchor:state.sourceAnchor,source_lineage_snapshot_hash:sourceHashes.lineage,source_semantic_snapshot_hash:sourceHashes.semantic},result_semantic_snapshot_hash:sourceHashes.semantic,active_head_count:active,tombstone_head_count:tombstone}),revision:Revision={record_type:'epoch_migration',record_schema:'epoch-migration-sw-v1',record_id:await deterministicId(['rotation-migration-record-v1',state.rotationId],16),revision_id:await deterministicId(['rotation-migration-revision-v1',state.rotationId]),parent_revision_ids:[],record_status:'control',record_data:migrationData,migration_origin:null,protocol_created_at:state.createdAt};await this.repository.prepareRotationEnvelope(\`${'${state.rotationId}'}:migration\`,context,revision);await this.hit('after-migration-envelope')\n`
  s=replaceOnce(s,oldCopy,newCopy,'deterministic copy and migration revisions')
  const oldAnnouncement=`  private async prepareAnnouncement(state:ConcreteRotationState):Promise<void>{const source=this.source??await this.repository.verifiedActiveEpoch(),context=await this.context(state),revision=await this.repository.rotationRevision(\`${'${state.rotationId}'}:announcement\`,()=>({record_type:'rotation_announcement',record_schema:'rotation-announcement-sw-v1',record_id:base64Url(randomBytes(16)),revision_id:base64Url(randomBytes(32)),parent_revision_ids:[],record_status:'control',record_data:{rotation_id:state.rotationId,from_epoch_id:source.context.epochId,successor_epoch_id:state.newEpochId,successor_creation_locator:state.creationLocator,successor_manifest_fingerprint:context.manifestFingerprint,rotation_kind:'normal'},migration_origin:null,protocol_created_at:state.createdAt}));const envelope=await this.repository.prepareRotationEnvelope(\`${'${state.rotationId}'}:announcement\`,source.context,revision);await this.repository.putArtifact(\`${'${state.rotationId}'}:announcement\`,envelope);await this.hit('after-announcement-envelope')}\n`
  const newAnnouncement=`  private async prepareAnnouncement(state:ConcreteRotationState):Promise<void>{const source=this.source??await this.repository.verifiedActiveEpoch(),context=await this.context(state),revision:Revision={record_type:'rotation_announcement',record_schema:'rotation-announcement-sw-v1',record_id:await deterministicId(['rotation-announcement-record-v1',state.rotationId],16),revision_id:await deterministicId(['rotation-announcement-revision-v1',state.rotationId]),parent_revision_ids:[],record_status:'control',record_data:{rotation_id:state.rotationId,from_epoch_id:source.context.epochId,successor_epoch_id:state.newEpochId,successor_creation_locator:state.creationLocator,successor_manifest_fingerprint:context.manifestFingerprint,rotation_kind:'normal'},migration_origin:null,protocol_created_at:state.createdAt};const envelope=await this.repository.prepareRotationEnvelope(\`${'${state.rotationId}'}:announcement\`,source.context,revision);await this.repository.putArtifact(\`${'${state.rotationId}'}:announcement\`,envelope);await this.hit('after-announcement-envelope')}\n`
  s=replaceOnce(s,oldAnnouncement,newAnnouncement,'deterministic announcement revision')
  write(path,s)
}

{
  const path='src/test/sync.test.ts'
  let s=read(path)
  s=replaceOnce(s,
`function setup(envelope: PreparedEnvelope|readonly PreparedEnvelope[]) { let anchor: RemoteAnchor|null=null; const durable:string[]=[];let generation=1; const transport=new InMemoryTransport(); transport.remotes.set('remote',{manifest,rows:[]}); const store:CoordinatorStore={readAnchor:async()=>anchor,pending:async()=>Array.isArray(envelope)?envelope:[envelope as PreparedEnvelope],generation:async()=>generation,commitDurable:async(id,next,expected)=>{expect(expected).toBe(generation);durable.push(id);anchor=next;generation++}};`,
`function setup(envelope: PreparedEnvelope|readonly PreparedEnvelope[]) { let anchor: RemoteAnchor|null=null; const durable:string[]=[];let generation=1; const transport=new InMemoryTransport(); transport.remotes.set('remote',{manifest,rows:[]}); const store:CoordinatorStore={readAnchor:async()=>anchor,pending:async()=>Array.isArray(envelope)?envelope:[envelope as PreparedEnvelope],generation:async()=>generation,commitVerifiedPull:async(_rows,next,expected)=>{expect(expected).toBe(generation);anchor=next;return ++generation},commitDurable:async(id,next,expected)=>{expect(expected).toBe(generation);durable.push(id);anchor=next;generation++}};`,
'sync test store persists pull')
  s=replaceOnce(s,
`  it('advances the generation independently for three pending envelopes',async()=>{const envelopes=[1,2,3].map(value=>({...envelope,envelopeId:baseId(value)}));const {coordinator,getDurables,generation}=setup(envelopes);coordinator.connected();await coordinator.pullVerify();await coordinator.pushPending();expect(getDurables()).toEqual(envelopes.map(item=>item.envelopeId));expect(generation()).toBe(4)})\n`,
`  it('advances the generation independently for three pending envelopes',async()=>{const envelopes=[1,2,3].map(value=>({...envelope,envelopeId:baseId(value)}));const {coordinator,getDurables,generation}=setup(envelopes);coordinator.connected();await coordinator.pullVerify();await coordinator.pushPending();expect(getDurables()).toEqual(envelopes.map(item=>item.envelopeId));expect(generation()).toBe(5)})\n  it('persists a pure-pull anchor and rejects a later rollback',async()=>{const {coordinator,transport}=setup([]);const rows=[1,2,3].map(value=>[baseId(value),envelope.iv,envelope.ciphertext] as const);transport.remotes.set('remote',{manifest,rows});coordinator.connected();await coordinator.pullVerify();coordinator.connected();transport.remotes.set('remote',{manifest,rows:rows.slice(0,2)});await expect(coordinator.pullVerify()).rejects.toThrow(/rollback|prefix|shorter/i);expect(coordinator.state).toBe('security_blocked')})\n`,
'pure pull rollback test')
  write(path,s)
}

{
  const path='src/test/localDatabase.test.ts'
  let s=read(path)
  s=replaceOnce(s,
`describe('immutable envelope write authority',()=>{it('uses the verified envelope head after the revision cache is deleted',async()=>{\n`,
`describe('immutable envelope write authority',()=>{it('uses the verified envelope head without a plaintext revision cache',async()=>{\n`,
'rename plaintext cache test')
  s=replaceOnce(s,
`  const clear=raw.transaction(db.__localDatabaseTesting.STORES.revisions,'readwrite');clear.objectStore(db.__localDatabaseTesting.STORES.revisions).clear();await new Promise<void>((resolve,reject)=>{clear.oncomplete=()=>resolve();clear.onerror=()=>reject(clear.error)})\n  await db.putRecord`,
`  expect(raw.objectStoreNames.contains('revisions')).toBe(false)\n  await db.putRecord`,
'test no revisions store')
  s=replaceOnce(s,
`describe('productive IndexedDB coordinator store',()=>{it('persists every envelope durable and reconstructs an empty outbox after reload',async()=>{`,
`describe('productive IndexedDB coordinator store',()=>{it('persists a verified pure-pull anchor before any push',async()=>{\n  const db=await import('../data/localDatabase'),raw=await db.__localDatabaseTesting.openDatabase(),active=await db.__localDatabaseTesting.loadEpoch(raw),store=new db.IndexedDbCoordinatorStore(active.context.epochId),transport=new InMemoryTransport(),remoteId='pure-pull-idb',manifest=['sync-v5','5','AAAAAAAAAAAAAAAA','AAAAAAAAAAAAAAAAAAAAAA'];transport.remotes.set(remoteId,{manifest,rows:[]});const coordinator=new SingleWriterCoordinator(active.context.diaryId,active.context.epochId,remoteId,transport,new GoogleSheetsSingleWriterProfileCodec(new TestRemoteVerifier()),store);coordinator.connected();await coordinator.pullVerify();expect((await db.__localDatabaseTesting.loadEpoch(raw)).state.remote_anchor?.covered_row_count).toBe(0)\n})\n\nit('persists every envelope durable and reconstructs an empty outbox after reload',async()=>{`,
'IDB pure pull anchor test')
  write(path,s)
}
