import { deriveStateMacKey, hmacSha256, randomBytes, sha256 } from './crypto/core'
import { arrayBuffer, base64Url, concatBytes, equalBytes, fixedBase64Url, fromBase64Url, uint64be, utf8 } from './crypto/bytes'
import { canonicalBytes } from './crypto/canonical'
import type { PreparedEnvelope } from './envelopes'
import type { RemoteAnchor } from '../sync/core/prefix'

export type EpochStatus='local_offline'|'remote_bound'|'active'|'offline_restored'|'retired'|'orphaned'
export interface SecurityStateRef {operation_id:string;state:string;state_record_hash:string}
export interface EpochLocalSecurityState {local_state_version:5;diary_id:string;epoch_id:string;key_id:string;manifest_fingerprint:string;recovery_generation:number;recovery_urs_commitment:string;remote_binding:null|{provider_id:'google-sheets-single-writer-v1';remote_resource_id:string;remote_identity_binding:string};remote_anchor:RemoteAnchor|null;epoch_status:EpochStatus;operation_generation:number;rotation_state_ref:SecurityStateRef|null;migration_state_ref:SecurityStateRef|null;local_journal_count:number;local_journal_hash:string}
export interface RootWrap {local_wrap_version:5;mode:'best-effort';diary_id:string;epoch_id:string;key_id:string;manifest_fingerprint:string;wrap_id:string;wrap_iv:string;wrapped_root_key:string;mode_metadata:Record<string,never>}
const zero=new Uint8Array([0])
export async function journalInitial(diaryId:string,epochId:string):Promise<string>{return base64Url(await sha256(concatBytes(utf8('eds-diary/local-journal/v5'),zero,fixedBase64Url(diaryId,16),fixedBase64Url(epochId,16))))}
export async function journalNext(previous:string,sequence:number,envelope:Pick<PreparedEnvelope,'envelopeId'|'iv'|'ciphertext'>):Promise<string>{const entry=await sha256(canonicalBytes([envelope.envelopeId,envelope.iv,envelope.ciphertext]));return base64Url(await sha256(concatBytes(fixedBase64Url(previous,32),uint64be(sequence),entry)))}
export async function stateTag(rootKey:Uint8Array,epochSalt:Uint8Array,state:EpochLocalSecurityState):Promise<string>{return base64Url(await hmacSha256(await deriveStateMacKey(rootKey,epochSalt),canonicalBytes(state as never)))}
export async function verifyStateTag(rootKey:Uint8Array,epochSalt:Uint8Array,state:EpochLocalSecurityState,tag:string):Promise<void>{if(!equalBytes(fixedBase64Url(tag,32),fromBase64Url(await stateTag(rootKey,epochSalt,state))))throw new Error('Local security state MAC failed.')}
const wrapAad=(wrap:Omit<RootWrap,'wrapped_root_key'|'wrap_iv'>)=>canonicalBytes(wrap as never)
export async function createBestEffortRootWrap(rootKey:Uint8Array,wrappingKey:CryptoKey,identity:Pick<RootWrap,'diary_id'|'epoch_id'|'key_id'|'manifest_fingerprint'>,id=randomBytes(16),iv=randomBytes(12)):Promise<RootWrap>{if(rootKey.byteLength!==32||wrappingKey.extractable)throw new Error('Invalid best-effort wrapping boundary.');const header={local_wrap_version:5 as const,mode:'best-effort'as const,...identity,wrap_id:base64Url(id),mode_metadata:{}};const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv:arrayBuffer(iv),additionalData:arrayBuffer(wrapAad(header)),tagLength:128},wrappingKey,arrayBuffer(rootKey));return{...header,wrap_iv:base64Url(iv),wrapped_root_key:base64Url(new Uint8Array(ciphertext))}}
export async function openBestEffortRootWrap(wrap:RootWrap,wrappingKey:CryptoKey):Promise<Uint8Array>{const{wrap_iv,wrapped_root_key,...header}=wrap;return new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:arrayBuffer(fixedBase64Url(wrap_iv,12)),additionalData:arrayBuffer(wrapAad(header)),tagLength:128},wrappingKey,arrayBuffer(fromBase64Url(wrapped_root_key))))}
export async function withDiaryLock<T>(diaryId:string,operation:()=>Promise<T>):Promise<T>{const manager=globalThis.navigator?.locks;if(!manager){if(typeof window!=='undefined')throw new Error('Web Locks are required for secure mutations.');return operation()}return manager.request(`eds-diary/security/${diaryId}`,{mode:'exclusive'},operation)}
